---
- hosts: ansible_server
  become: true

  tasks:
    - name: Remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/attachments.txt
        - /tmp/body.txt
        - /tmp/uptime_bash_report.txt
        - /tmp/24h_report.txt
        - /tmp/unreachable_report.txt
      run_once: true
      ignore_errors: true

- hosts: ansible_server
  become: true
  tasks:

    - name: Calculate number of hosts
      shell: "cat /home/X/hostgroups/hosts|wc -l"
      register: totalnumberofsystems
      ignore_errors: true

    - name: Running uptime script on all systems
      shell: "sh /home/X/ansible/remote_scripts/hostuptime.sh >> /tmp/uptime_bash_report.txt"
      async: 600  # 600 seconds // 10 min
      poll: 5     # poll until the job completes
      become_user: X
      ignore_errors: true

    - name: Checking for unrachable servers
      shell: "sh /home/X/ansible/remote_scripts/unreachable2.sh >> /tmp/unreachable_report.txt"
      async: 10  # 10 seconds
      poll: 0     # poll until the job completes
      become_user: X
      ignore_errors: true

    - name: Generating 24h report
      shell: |
        grep -v 'day' /tmp/uptime_bash_report.txt >> /tmp/24h_report.txt
      become_user: X
      ignore_errors: true

    - name: Check if 24h report has anything to report
      shell: "cat /tmp/24h_report.txt"
      register: report24
      ignore_errors: true

    - name: Check if unreachable report has anything to report
      shell: "cat /tmp/unreachable_report.txt"
      register: unreachable
      ignore_errors: true

    - name: Generating uptime report 2
      shell: "cat /tmp/uptime_bash_report.txt|grep up |wc -l"
      register: totalnumberofpingablesystems
      ignore_errors: true

    - name: Generating uptime report 3
      shell: 'echo " - Attached uptime report generated by Ansible and bash script." >> /tmp/body.txt; echo " - Number of pingable systems: {{ totalnumberofpingablesystems.stdout }} out of expected  {{ totalnumberofsystems.stdout }} systems" >> /tmp/body.txt'
      ignore_errors: true

    - name: Generating uptime report 4
      shell: "ls /tmp/uptime_bash_report.txt 2>/dev/null >> /tmp/attachments.txt; chmod 777 /tmp/attachments.txt;"
      ignore_errors: true

    - name: Generating uptime report 5
      shell: "cat /tmp/body.txt"
      register: body
      ignore_errors: true

    - name: Generating uptime report 6
      shell: "ls /tmp/unreachable_report.txt 2>/dev/null >> /tmp/attachments.txt;"
      when:
        - unreachable.stdout != ""
      ignore_errors: true

    - name: Generating uptime report 7
      shell: "ls /tmp/24h_report.txt 2>/dev/null >> /tmp/attachments.txt;"
      when:
        - report24.stdout != ""
      ignore_errors: true

    - name: Collect all attachments
      shell: "cat /tmp/attachments.txt"
      register: attachments
      ignore_errors: true

    - name: Sending an email
      become: false
      mail:
        host: localhost
        port: 25
        from: P
        to: Z
        subject: Linux health check report! Please review attached uptime reports.
        body: "{{ body.stdout }}"
        attach: "{{ attachments.stdout_lines | join(',') }}"
      run_once: true
      ignore_errors: true
      when:
        - attachments is defined
        - attachments.stdout != ""
